### PR TITLE
fix: modify config.ts to fix zh page(alibaba#214) and cover(alibaba#218)

### LINKED ISSUE #214: Chinese document display error
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen

If I directly access the Chinese link mentioned in the project README: https://alibaba.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

There is a problem with the Chinese documentation page

image

### Reproduction way

https://alibaba.github.io/yalantinglibs/zh/guide/coro-rpc-intro.html

### Anything else

Enter from the[ English interface](https://alibaba.github.io/yalantinglibs/guide/what-is-yalantinglibs.html) and switch to the Chinese display correctly

Maybe you could simply delete the Chinese entrance？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by SoTosorrow**
## Why
Closes #214

## What is changing

changed:
1:delete the part of gen_sh.sh for fix style
2:modify themeConfig of the .vitepress/config.ts
attention:
this PR won't push the generate docs, only config changed are involved. so there have some conflicts of gen-docs.

It should be regenerated after merge.

### CODE REVIEW

**Comment by SoTosorrow** [comment]
@PikachuHyA @qicosmos Could you please take a review?

**Comment by qicosmos** [comment]
> @PikachuHyA @qicosmos Could you please take a review?

Could you solve the conflicts, after that i can look at the page from github action.

**Comment by PikachuHyA** [comment]
@SoTosorrow 
please submit config only
I will generate the html files later.

**Comment by PikachuHyA** [comment]
I will solve the conflict.

**Comment by PikachuHyA** [comment]
@SoTosorrow please check the new Files Changed

https://github.com/alibaba/yalantinglibs/pull/225/files

I'm not sure if the code is deleted by mistake.

**Review by SoTosorrow — COMMENTED** [review]
no problem, LGTM :)

**Comment by PikachuHyA** [comment]
thanks
great

**Pull request merged**
