### PR TITLE
bazel build support

### PR DESCRIPTION
**Pull request by ashione**
## What is changing
New feature:  bazel compile supporting

### CODE REVIEW

**Comment by ashione** [comment]
@qicosmos please help me to review these changes.

**Comment by qicosmos** [comment]
lack of doctest.h

**Comment by ashione** [comment]
What can I know from that bazel workflow configuration just contains the following :
```yaml
      - name: Build
        working-directory: ${{github.workspace}}
        run: bazel build --action_env=CXX=clang++-17 --action_env=CC=clang-17 ...

      - name: Test
        working-directory: ${{github.workspace}}
        run: bazel test --action_env=CXX=clang++-17 --action_env=CC=clang-17 --test_output=errors ...
```

@qicosmos

**Comment by ashione** [comment]
I'm not sure why test failure there : https://github.com/alibaba/yalantinglibs/actions/runs/8107243077/job/22158576180?pr=613, but there are no codes be modification in these changes.
@qicosmos

**Comment by poor-circle** [comment]
USE _GLIBCXX_USE_CXX11_ABI=0 can't deserialize wstring/u8string/u16string with coredump. see https://github.com/alibaba/yalantinglibs/issues/615

**Review by qicosmos — APPROVED** [review]
LGTM

**Pull request merged**
