### PR TITLE
Fix cmake

### PR DESCRIPTION
**Pull request by sunflower-knight**
## Why
1. clean code
2. fix bug 
3. move openssl files in top dir into /src/coro_rpc/tests to make the code structure  clean  https://github.com/alibaba/yalantinglibs/issues/97#issue-1478986186

## What is changing
1. cmake-module-manage
now there will  not have Build_ylt_all=ON anymore. Just use some predefind default option for module to build.
coro_rpc struct_pack struck_json  predefind ON to compile
For module in src/util   default value is OFF, because I find it useless for the whole project . maybe someone will use it one day.
By the way, this change will not change the CI behaviour before. 

4. fix cmake-bug for struct pack benchmark   https://github.com/alibaba/yalantinglibs/issues/103#issue-1481507375 . 
I test it in `ubuntu2204` `clang-14` `ninja` `protoc-22.*` `ptobuf-dev-12`

### CODE REVIEW

**Comment by sunflower-knight** [comment]
sum: clean cmake code and fix cmake bug . 
Hope that  reviewer can squash as one commit with a name about cmake when you rebase  or merge.  `clean and fix Cmake code`

**Comment by PikachuHyA** [comment]
LGTM

**Comment by PikachuHyA** [comment]
> I want to use add_custom_target to make sure that commands will execute before the benchmark-target compile.

for protoc, see https://cmake.org/cmake/help/latest/module/FindProtobuf.html?highlight=protoc

```
find_package(Protobuf REQUIRED)
include_directories(${Protobuf_INCLUDE_DIRS})
include_directories(${CMAKE_CURRENT_BINARY_DIR})
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS foo.proto)
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS EXPORT_MACRO DLL_EXPORT foo.proto)
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS DESCRIPTORS PROTO_DESCS foo.proto)
protobuf_generate_python(PROTO_PY foo.proto)
add_executable(bar bar.cc ${PROTO_SRCS} ${PROTO_HDRS})
target_link_libraries(bar ${Protobuf_LIBRARIES})
```

all work will be done after https://github.com/alibaba/yalantinglibs/pull/90 merged.
but the refactor of benchmark is not ready now.

**Comment by sunflower-knight** [comment]
> > I want to use add_custom_target to make sure that commands will execute before the benchmark-target compile.
> 
> for protoc, see https://cmake.org/cmake/help/latest/module/FindProtobuf.html?highlight=protoc
> 
> ```
> find_package(Protobuf REQUIRED)
> include_directories(${Protobuf_INCLUDE_DIRS})
> include_directories(${CMAKE_CURRENT_BINARY_DIR})
> protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS foo.proto)
> protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS EXPORT_MACRO DLL_EXPORT foo.proto)
> protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS DESCRIPTORS PROTO_DESCS foo.proto)
> protobuf_generate_python(PROTO_PY foo.proto)
> add_executable(bar bar.cc ${PROTO_SRCS} ${PROTO_HDRS})
> target_link_libraries(bar ${Protobuf_LIBRARIES})
> ```
> 
> all work will be done after #90 merged. but the refactor of benchmark is not ready now.

I test this method and it work well . clean and better . Thanks ! I learn someting new.  **It is much better than my code.**

When you rebase the main ( my code has merge in)  some code may need to keep.In struct_pack benchmark CMakeLists . 
```
if(NOT BUILD_SP_BENCHMARK)
    message(WARNING "additional BUILD_SP_BENCHMARK=ON needed for struct_pack benchmark")
    return()
endif()
```



-------------------------------------------------------------------------


Find protoc ,  some  people in ubuntu will use apt to install protobuf-dev , this dev don't have protoc. 
I think add the code blow  can make a error or warning at the cmake-configure time rather than cmake-build time. 
But if you think it is needless ( you can add some instruction for user in readme.md even some shell scripts to help than install ) 
just delete this code
```
find_program(PROTOC_CXX_FOUND protoc DOC "Protobuf Compiler (protoc)")
if(NOT PROTOC_CXX_FOUND)
    message(FATAL_ERROR "install protoc before struct_pack benchmark")
endif()
```

**Pull request merged**
