### PR TITLE
[CI] use ccache speed up CI 

### PR DESCRIPTION
**Pull request by sunflower-knight**
## Why
speed up CI time to 1min

"Closes ##117"

## What is changing
[click to see the new CI time ](https://github.com/sunflower-knight/yalantinglibs/actions/runs/4710226995/usage)
## Example

### CODE REVIEW

**Comment by poor-circle** [comment]
Thank you!

**Comment by sunflower-knight** [comment]
In the latest commit , 
I use  Window+MSVC+Ninja+Ccache.
But ccache can be used in Release type only in this toolchain. 
In this toolchain with Release type  ,CI time almost 2min. Also somewhere we can speed up in the future.

So I change window CI type from Debug to Release.
If you think window debug type is very important in CI just add Debug in window.yml .

But notice that:it is very slow in window debug type. 
If you want to use ccache in window debug , theres is some links can help you. 

https://github.com/ccache/ccache/wiki/MS-Visual-Studio
https://github.com/frerich/clcache/issues/30
https://github.com/mozilla/sccache (See Readme)
https://github.com/mozilla/sccache/issues/956
https://github.com/mbitsnbites/buildcache/issues/104

For example use `Do not use /Zi debugging (/Z7 is okay)` in debug type , ccache maybe can work. 
In this way, msvc will not generate pdb.  
But for CI ,  it can be accepted.

**Comment by PikachuHyA** [comment]
Great

**Comment by PikachuHyA** [comment]
LGTM

**Pull request merged**
