### PR TITLE
friendly-cmake

### PR DESCRIPTION
**Pull request by sunflower-knight**
## Why
1. more easily for developer who use cmake-gui 
2. add more option for developer  like  `Warning for all project or a single target` `ASAN for all project or a single target`
3. manager a lot of cmake content in different files like "build.cmake" "install.cmake" . It will be uesfule for future develop .for example if you want to add `http-module` , you only need to change `module.cmake` . And you should `turn on warning or ASAN for http-module` only.  

## What is changing
1. for users 
**cmake-build api**  has changed  if you want to compile some of the all projects in CLI. 
You shuld use -DBuild_coro_rpc=ON -DBuild_struct_pack=ON  
But you can use cmake-gui more easyily  .....
2.  for developers 
add some function for developers and  cmake become easyier to read 

## Example
image

### CODE REVIEW

**Comment by PikachuHyA** [comment]
> You shuld use -Dcore_rpc=ON Dstruct_pack=ON

type?

**Comment by sunflower-knight** [comment]
> > You shuld use -Dcore_rpc=ON Dstruct_pack=ON
> 
> type?


I never use type when I want to transfer a var to Cmake in terminal CLI before. It work well. 
e.g. -DBUILD_ylt_coro_rpc=ON.

maybe cmake will know the var is boolean and check it. 

I use Ubuntu20.04 and Cmake 3.20 now.

**Comment by PikachuHyA** [comment]
sorry, I mean typo. mmmm
`-Dcore_rpc=ON` -> `-Dcoro_rpc=ON`

**Comment by PikachuHyA** [comment]
> This branch has conflicts that must be resolved

I will solve the conflicts after all CI finished.

**Comment by sunflower-knight** [comment]
> sorry, I mean typo. mmmm `-Dcore_rpc=ON` -> `-Dcoro_rpc=ON`

oh！I will edit  this typo

**Comment by PikachuHyA** [comment]
something wrong on Windows
I will check these error

**Comment by sunflower-knight** [comment]
I rebase the `main` branch to catch-up the upsteam ( I know @PikachuHyA did it by merge several hours ago but i think reaba is better ) 
and I squeeze @PikachuHyA 's 2 commit about `module.cmake` into  1 commit to make it clean in git-log.

i try my best to make git-log clean ,at the same time , I will not erase other developers commmit blam. 

if you have any better method,please tell me .  I am greenhand in  `github-fork`

**Comment by PikachuHyA** [comment]
LGTM

**Comment by PikachuHyA** [comment]
Thanks for your contribution.
I have merged all your PRs. 
you can check the history:  https://github.com/alibaba/yalantinglibs/commits/main, which is produced by
 `squash and merge`.

I noticed you also submit some issues.
Any PR is appreciated. We all are willing to review your code.

**Pull request merged**
